//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DetiInteract.Guide.DSDWS {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="ArrayOfInt", Namespace="http://dsd.av.it.pt/dsdws", ItemName="int")]
    [System.SerializableAttribute()]
    public class ArrayOfInt : System.Collections.Generic.List<int> {
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://dsd.av.it.pt/dsdws", ConfigurationName="DSDWS.WSSoap")]
    public interface WSSoap {
        
        // CODEGEN: Generating message contract since element name getSemestresResult from namespace http://dsd.av.it.pt/dsdws is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://dsd.av.it.pt/dsdws/getSemestres", ReplyAction="*")]
        DetiInteract.Guide.DSDWS.getSemestresResponse getSemestres(DetiInteract.Guide.DSDWS.getSemestresRequest request);
        
        // CODEGEN: Generating message contract since element name getTiposSalaResult from namespace http://dsd.av.it.pt/dsdws is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://dsd.av.it.pt/dsdws/getTiposSala", ReplyAction="*")]
        DetiInteract.Guide.DSDWS.getTiposSalaResponse getTiposSala(DetiInteract.Guide.DSDWS.getTiposSalaRequest request);
        
        // CODEGEN: Generating message contract since element name getSalasResult from namespace http://dsd.av.it.pt/dsdws is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://dsd.av.it.pt/dsdws/getSalas", ReplyAction="*")]
        DetiInteract.Guide.DSDWS.getSalasResponse getSalas(DetiInteract.Guide.DSDWS.getSalasRequest request);
        
        // CODEGEN: Generating message contract since element name getCursosResult from namespace http://dsd.av.it.pt/dsdws is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://dsd.av.it.pt/dsdws/getCursos", ReplyAction="*")]
        DetiInteract.Guide.DSDWS.getCursosResponse getCursos(DetiInteract.Guide.DSDWS.getCursosRequest request);
        
        // CODEGEN: Generating message contract since element name getDepartamentosResult from namespace http://dsd.av.it.pt/dsdws is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://dsd.av.it.pt/dsdws/getDepartamentos", ReplyAction="*")]
        DetiInteract.Guide.DSDWS.getDepartamentosResponse getDepartamentos(DetiInteract.Guide.DSDWS.getDepartamentosRequest request);
        
        // CODEGEN: Generating message contract since element name getAreasResult from namespace http://dsd.av.it.pt/dsdws is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://dsd.av.it.pt/dsdws/getAreas", ReplyAction="*")]
        DetiInteract.Guide.DSDWS.getAreasResponse getAreas(DetiInteract.Guide.DSDWS.getAreasRequest request);
        
        // CODEGEN: Generating message contract since element name getSubAreasResult from namespace http://dsd.av.it.pt/dsdws is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://dsd.av.it.pt/dsdws/getSubAreas", ReplyAction="*")]
        DetiInteract.Guide.DSDWS.getSubAreasResponse getSubAreas(DetiInteract.Guide.DSDWS.getSubAreasRequest request);
        
        // CODEGEN: Generating message contract since element name getDocentesResult from namespace http://dsd.av.it.pt/dsdws is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://dsd.av.it.pt/dsdws/getDocentes", ReplyAction="*")]
        DetiInteract.Guide.DSDWS.getDocentesResponse getDocentes(DetiInteract.Guide.DSDWS.getDocentesRequest request);
        
        // CODEGEN: Generating message contract since element name getDocentesAnoResult from namespace http://dsd.av.it.pt/dsdws is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://dsd.av.it.pt/dsdws/getDocentesAno", ReplyAction="*")]
        DetiInteract.Guide.DSDWS.getDocentesAnoResponse getDocentesAno(DetiInteract.Guide.DSDWS.getDocentesAnoRequest request);
        
        // CODEGEN: Generating message contract since element name getDisciplinasResult from namespace http://dsd.av.it.pt/dsdws is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://dsd.av.it.pt/dsdws/getDisciplinas", ReplyAction="*")]
        DetiInteract.Guide.DSDWS.getDisciplinasResponse getDisciplinas(DetiInteract.Guide.DSDWS.getDisciplinasRequest request);
        
        // CODEGEN: Generating message contract since element name getDisciplinasAnoResult from namespace http://dsd.av.it.pt/dsdws is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://dsd.av.it.pt/dsdws/getDisciplinasAno", ReplyAction="*")]
        DetiInteract.Guide.DSDWS.getDisciplinasAnoResponse getDisciplinasAno(DetiInteract.Guide.DSDWS.getDisciplinasAnoRequest request);
        
        // CODEGEN: Generating message contract since element name getTurmasResult from namespace http://dsd.av.it.pt/dsdws is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://dsd.av.it.pt/dsdws/getTurmas", ReplyAction="*")]
        DetiInteract.Guide.DSDWS.getTurmasResponse getTurmas(DetiInteract.Guide.DSDWS.getTurmasRequest request);
        
        // CODEGEN: Generating message contract since element name getAulasResult from namespace http://dsd.av.it.pt/dsdws is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://dsd.av.it.pt/dsdws/getAulas", ReplyAction="*")]
        DetiInteract.Guide.DSDWS.getAulasResponse getAulas(DetiInteract.Guide.DSDWS.getAulasRequest request);
        
        // CODEGEN: Generating message contract since element name getTurmasHoraResult from namespace http://dsd.av.it.pt/dsdws is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://dsd.av.it.pt/dsdws/getTurmasHora", ReplyAction="*")]
        DetiInteract.Guide.DSDWS.getTurmasHoraResponse getTurmasHora(DetiInteract.Guide.DSDWS.getTurmasHoraRequest request);
        
        // CODEGEN: Generating message contract since element name getWishListResult from namespace http://dsd.av.it.pt/dsdws is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://dsd.av.it.pt/dsdws/getWishList", ReplyAction="*")]
        DetiInteract.Guide.DSDWS.getWishListResponse getWishList(DetiInteract.Guide.DSDWS.getWishListRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getSemestresRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getSemestres", Namespace="http://dsd.av.it.pt/dsdws", Order=0)]
        public DetiInteract.Guide.DSDWS.getSemestresRequestBody Body;
        
        public getSemestresRequest() {
        }
        
        public getSemestresRequest(DetiInteract.Guide.DSDWS.getSemestresRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://dsd.av.it.pt/dsdws")]
    public partial class getSemestresRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int Rev;
        
        public getSemestresRequestBody() {
        }
        
        public getSemestresRequestBody(int Rev) {
            this.Rev = Rev;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getSemestresResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getSemestresResponse", Namespace="http://dsd.av.it.pt/dsdws", Order=0)]
        public DetiInteract.Guide.DSDWS.getSemestresResponseBody Body;
        
        public getSemestresResponse() {
        }
        
        public getSemestresResponse(DetiInteract.Guide.DSDWS.getSemestresResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://dsd.av.it.pt/dsdws")]
    public partial class getSemestresResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public DetiInteract.DSDBroker.DSDWS.Semestre[] getSemestresResult;
        
        public getSemestresResponseBody() {
        }
        
        public getSemestresResponseBody(DetiInteract.DSDBroker.DSDWS.Semestre[] getSemestresResult) {
            this.getSemestresResult = getSemestresResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getTiposSalaRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getTiposSala", Namespace="http://dsd.av.it.pt/dsdws", Order=0)]
        public DetiInteract.Guide.DSDWS.getTiposSalaRequestBody Body;
        
        public getTiposSalaRequest() {
        }
        
        public getTiposSalaRequest(DetiInteract.Guide.DSDWS.getTiposSalaRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://dsd.av.it.pt/dsdws")]
    public partial class getTiposSalaRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int Rev;
        
        public getTiposSalaRequestBody() {
        }
        
        public getTiposSalaRequestBody(int Rev) {
            this.Rev = Rev;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getTiposSalaResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getTiposSalaResponse", Namespace="http://dsd.av.it.pt/dsdws", Order=0)]
        public DetiInteract.Guide.DSDWS.getTiposSalaResponseBody Body;
        
        public getTiposSalaResponse() {
        }
        
        public getTiposSalaResponse(DetiInteract.Guide.DSDWS.getTiposSalaResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://dsd.av.it.pt/dsdws")]
    public partial class getTiposSalaResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public DetiInteract.DSDBroker.DSDWS.TipoSala[] getTiposSalaResult;
        
        public getTiposSalaResponseBody() {
        }
        
        public getTiposSalaResponseBody(DetiInteract.DSDBroker.DSDWS.TipoSala[] getTiposSalaResult) {
            this.getTiposSalaResult = getTiposSalaResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getSalasRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getSalas", Namespace="http://dsd.av.it.pt/dsdws", Order=0)]
        public DetiInteract.Guide.DSDWS.getSalasRequestBody Body;
        
        public getSalasRequest() {
        }
        
        public getSalasRequest(DetiInteract.Guide.DSDWS.getSalasRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://dsd.av.it.pt/dsdws")]
    public partial class getSalasRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int IDDepartamento;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public int Rev;
        
        public getSalasRequestBody() {
        }
        
        public getSalasRequestBody(int IDDepartamento, int Rev) {
            this.IDDepartamento = IDDepartamento;
            this.Rev = Rev;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getSalasResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getSalasResponse", Namespace="http://dsd.av.it.pt/dsdws", Order=0)]
        public DetiInteract.Guide.DSDWS.getSalasResponseBody Body;
        
        public getSalasResponse() {
        }
        
        public getSalasResponse(DetiInteract.Guide.DSDWS.getSalasResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://dsd.av.it.pt/dsdws")]
    public partial class getSalasResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public DetiInteract.DSDBroker.DSDWS.Sala[] getSalasResult;
        
        public getSalasResponseBody() {
        }
        
        public getSalasResponseBody(DetiInteract.DSDBroker.DSDWS.Sala[] getSalasResult) {
            this.getSalasResult = getSalasResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getCursosRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getCursos", Namespace="http://dsd.av.it.pt/dsdws", Order=0)]
        public DetiInteract.Guide.DSDWS.getCursosRequestBody Body;
        
        public getCursosRequest() {
        }
        
        public getCursosRequest(DetiInteract.Guide.DSDWS.getCursosRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://dsd.av.it.pt/dsdws")]
    public partial class getCursosRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int IDDepartamento;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public int Rev;
        
        public getCursosRequestBody() {
        }
        
        public getCursosRequestBody(int IDDepartamento, int Rev) {
            this.IDDepartamento = IDDepartamento;
            this.Rev = Rev;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getCursosResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getCursosResponse", Namespace="http://dsd.av.it.pt/dsdws", Order=0)]
        public DetiInteract.Guide.DSDWS.getCursosResponseBody Body;
        
        public getCursosResponse() {
        }
        
        public getCursosResponse(DetiInteract.Guide.DSDWS.getCursosResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://dsd.av.it.pt/dsdws")]
    public partial class getCursosResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public DetiInteract.DSDBroker.DSDWS.Curso[] getCursosResult;
        
        public getCursosResponseBody() {
        }
        
        public getCursosResponseBody(DetiInteract.DSDBroker.DSDWS.Curso[] getCursosResult) {
            this.getCursosResult = getCursosResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getDepartamentosRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getDepartamentos", Namespace="http://dsd.av.it.pt/dsdws", Order=0)]
        public DetiInteract.Guide.DSDWS.getDepartamentosRequestBody Body;
        
        public getDepartamentosRequest() {
        }
        
        public getDepartamentosRequest(DetiInteract.Guide.DSDWS.getDepartamentosRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://dsd.av.it.pt/dsdws")]
    public partial class getDepartamentosRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int Rev;
        
        public getDepartamentosRequestBody() {
        }
        
        public getDepartamentosRequestBody(int Rev) {
            this.Rev = Rev;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getDepartamentosResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getDepartamentosResponse", Namespace="http://dsd.av.it.pt/dsdws", Order=0)]
        public DetiInteract.Guide.DSDWS.getDepartamentosResponseBody Body;
        
        public getDepartamentosResponse() {
        }
        
        public getDepartamentosResponse(DetiInteract.Guide.DSDWS.getDepartamentosResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://dsd.av.it.pt/dsdws")]
    public partial class getDepartamentosResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public DetiInteract.DSDBroker.DSDWS.Departamento[] getDepartamentosResult;
        
        public getDepartamentosResponseBody() {
        }
        
        public getDepartamentosResponseBody(DetiInteract.DSDBroker.DSDWS.Departamento[] getDepartamentosResult) {
            this.getDepartamentosResult = getDepartamentosResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getAreasRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getAreas", Namespace="http://dsd.av.it.pt/dsdws", Order=0)]
        public DetiInteract.Guide.DSDWS.getAreasRequestBody Body;
        
        public getAreasRequest() {
        }
        
        public getAreasRequest(DetiInteract.Guide.DSDWS.getAreasRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://dsd.av.it.pt/dsdws")]
    public partial class getAreasRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int Rev;
        
        public getAreasRequestBody() {
        }
        
        public getAreasRequestBody(int Rev) {
            this.Rev = Rev;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getAreasResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getAreasResponse", Namespace="http://dsd.av.it.pt/dsdws", Order=0)]
        public DetiInteract.Guide.DSDWS.getAreasResponseBody Body;
        
        public getAreasResponse() {
        }
        
        public getAreasResponse(DetiInteract.Guide.DSDWS.getAreasResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://dsd.av.it.pt/dsdws")]
    public partial class getAreasResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public DetiInteract.DSDBroker.DSDWS.Area[] getAreasResult;
        
        public getAreasResponseBody() {
        }
        
        public getAreasResponseBody(DetiInteract.DSDBroker.DSDWS.Area[] getAreasResult) {
            this.getAreasResult = getAreasResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getSubAreasRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getSubAreas", Namespace="http://dsd.av.it.pt/dsdws", Order=0)]
        public DetiInteract.Guide.DSDWS.getSubAreasRequestBody Body;
        
        public getSubAreasRequest() {
        }
        
        public getSubAreasRequest(DetiInteract.Guide.DSDWS.getSubAreasRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://dsd.av.it.pt/dsdws")]
    public partial class getSubAreasRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int Rev;
        
        public getSubAreasRequestBody() {
        }
        
        public getSubAreasRequestBody(int Rev) {
            this.Rev = Rev;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getSubAreasResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getSubAreasResponse", Namespace="http://dsd.av.it.pt/dsdws", Order=0)]
        public DetiInteract.Guide.DSDWS.getSubAreasResponseBody Body;
        
        public getSubAreasResponse() {
        }
        
        public getSubAreasResponse(DetiInteract.Guide.DSDWS.getSubAreasResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://dsd.av.it.pt/dsdws")]
    public partial class getSubAreasResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public DetiInteract.DSDBroker.DSDWS.SubArea[] getSubAreasResult;
        
        public getSubAreasResponseBody() {
        }
        
        public getSubAreasResponseBody(DetiInteract.DSDBroker.DSDWS.SubArea[] getSubAreasResult) {
            this.getSubAreasResult = getSubAreasResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getDocentesRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getDocentes", Namespace="http://dsd.av.it.pt/dsdws", Order=0)]
        public DetiInteract.Guide.DSDWS.getDocentesRequestBody Body;
        
        public getDocentesRequest() {
        }
        
        public getDocentesRequest(DetiInteract.Guide.DSDWS.getDocentesRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://dsd.av.it.pt/dsdws")]
    public partial class getDocentesRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int IDDepartamento;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public int Rev;
        
        public getDocentesRequestBody() {
        }
        
        public getDocentesRequestBody(int IDDepartamento, int Rev) {
            this.IDDepartamento = IDDepartamento;
            this.Rev = Rev;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getDocentesResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getDocentesResponse", Namespace="http://dsd.av.it.pt/dsdws", Order=0)]
        public DetiInteract.Guide.DSDWS.getDocentesResponseBody Body;
        
        public getDocentesResponse() {
        }
        
        public getDocentesResponse(DetiInteract.Guide.DSDWS.getDocentesResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://dsd.av.it.pt/dsdws")]
    public partial class getDocentesResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public DetiInteract.DSDBroker.DSDWS.Docente[] getDocentesResult;
        
        public getDocentesResponseBody() {
        }
        
        public getDocentesResponseBody(DetiInteract.DSDBroker.DSDWS.Docente[] getDocentesResult) {
            this.getDocentesResult = getDocentesResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getDocentesAnoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getDocentesAno", Namespace="http://dsd.av.it.pt/dsdws", Order=0)]
        public DetiInteract.Guide.DSDWS.getDocentesAnoRequestBody Body;
        
        public getDocentesAnoRequest() {
        }
        
        public getDocentesAnoRequest(DetiInteract.Guide.DSDWS.getDocentesAnoRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://dsd.av.it.pt/dsdws")]
    public partial class getDocentesAnoRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int IDDepartamento;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public int IDSemestre;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public int Rev;
        
        public getDocentesAnoRequestBody() {
        }
        
        public getDocentesAnoRequestBody(int IDDepartamento, int IDSemestre, int Rev) {
            this.IDDepartamento = IDDepartamento;
            this.IDSemestre = IDSemestre;
            this.Rev = Rev;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getDocentesAnoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getDocentesAnoResponse", Namespace="http://dsd.av.it.pt/dsdws", Order=0)]
        public DetiInteract.Guide.DSDWS.getDocentesAnoResponseBody Body;
        
        public getDocentesAnoResponse() {
        }
        
        public getDocentesAnoResponse(DetiInteract.Guide.DSDWS.getDocentesAnoResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://dsd.av.it.pt/dsdws")]
    public partial class getDocentesAnoResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public DetiInteract.DSDBroker.DSDWS.DocenteAno[] getDocentesAnoResult;
        
        public getDocentesAnoResponseBody() {
        }
        
        public getDocentesAnoResponseBody(DetiInteract.DSDBroker.DSDWS.DocenteAno[] getDocentesAnoResult) {
            this.getDocentesAnoResult = getDocentesAnoResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getDisciplinasRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getDisciplinas", Namespace="http://dsd.av.it.pt/dsdws", Order=0)]
        public DetiInteract.Guide.DSDWS.getDisciplinasRequestBody Body;
        
        public getDisciplinasRequest() {
        }
        
        public getDisciplinasRequest(DetiInteract.Guide.DSDWS.getDisciplinasRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://dsd.av.it.pt/dsdws")]
    public partial class getDisciplinasRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int IDDepartamento;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public int Rev;
        
        public getDisciplinasRequestBody() {
        }
        
        public getDisciplinasRequestBody(int IDDepartamento, int Rev) {
            this.IDDepartamento = IDDepartamento;
            this.Rev = Rev;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getDisciplinasResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getDisciplinasResponse", Namespace="http://dsd.av.it.pt/dsdws", Order=0)]
        public DetiInteract.Guide.DSDWS.getDisciplinasResponseBody Body;
        
        public getDisciplinasResponse() {
        }
        
        public getDisciplinasResponse(DetiInteract.Guide.DSDWS.getDisciplinasResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://dsd.av.it.pt/dsdws")]
    public partial class getDisciplinasResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public DetiInteract.DSDBroker.DSDWS.Disciplina[] getDisciplinasResult;
        
        public getDisciplinasResponseBody() {
        }
        
        public getDisciplinasResponseBody(DetiInteract.DSDBroker.DSDWS.Disciplina[] getDisciplinasResult) {
            this.getDisciplinasResult = getDisciplinasResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getDisciplinasAnoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getDisciplinasAno", Namespace="http://dsd.av.it.pt/dsdws", Order=0)]
        public DetiInteract.Guide.DSDWS.getDisciplinasAnoRequestBody Body;
        
        public getDisciplinasAnoRequest() {
        }
        
        public getDisciplinasAnoRequest(DetiInteract.Guide.DSDWS.getDisciplinasAnoRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://dsd.av.it.pt/dsdws")]
    public partial class getDisciplinasAnoRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int IDDepartamento;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public int IDSemestre;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public int Rev;
        
        public getDisciplinasAnoRequestBody() {
        }
        
        public getDisciplinasAnoRequestBody(int IDDepartamento, int IDSemestre, int Rev) {
            this.IDDepartamento = IDDepartamento;
            this.IDSemestre = IDSemestre;
            this.Rev = Rev;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getDisciplinasAnoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getDisciplinasAnoResponse", Namespace="http://dsd.av.it.pt/dsdws", Order=0)]
        public DetiInteract.Guide.DSDWS.getDisciplinasAnoResponseBody Body;
        
        public getDisciplinasAnoResponse() {
        }
        
        public getDisciplinasAnoResponse(DetiInteract.Guide.DSDWS.getDisciplinasAnoResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://dsd.av.it.pt/dsdws")]
    public partial class getDisciplinasAnoResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public DetiInteract.DSDBroker.DSDWS.DisciplinaAno[] getDisciplinasAnoResult;
        
        public getDisciplinasAnoResponseBody() {
        }
        
        public getDisciplinasAnoResponseBody(DetiInteract.DSDBroker.DSDWS.DisciplinaAno[] getDisciplinasAnoResult) {
            this.getDisciplinasAnoResult = getDisciplinasAnoResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getTurmasRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getTurmas", Namespace="http://dsd.av.it.pt/dsdws", Order=0)]
        public DetiInteract.Guide.DSDWS.getTurmasRequestBody Body;
        
        public getTurmasRequest() {
        }
        
        public getTurmasRequest(DetiInteract.Guide.DSDWS.getTurmasRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://dsd.av.it.pt/dsdws")]
    public partial class getTurmasRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int IDDepartamento;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public int IDSemestre;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public int Rev;
        
        public getTurmasRequestBody() {
        }
        
        public getTurmasRequestBody(int IDDepartamento, int IDSemestre, int Rev) {
            this.IDDepartamento = IDDepartamento;
            this.IDSemestre = IDSemestre;
            this.Rev = Rev;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getTurmasResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getTurmasResponse", Namespace="http://dsd.av.it.pt/dsdws", Order=0)]
        public DetiInteract.Guide.DSDWS.getTurmasResponseBody Body;
        
        public getTurmasResponse() {
        }
        
        public getTurmasResponse(DetiInteract.Guide.DSDWS.getTurmasResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://dsd.av.it.pt/dsdws")]
    public partial class getTurmasResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public DetiInteract.DSDBroker.DSDWS.Turma[] getTurmasResult;
        
        public getTurmasResponseBody() {
        }
        
        public getTurmasResponseBody(DetiInteract.DSDBroker.DSDWS.Turma[] getTurmasResult) {
            this.getTurmasResult = getTurmasResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getAulasRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getAulas", Namespace="http://dsd.av.it.pt/dsdws", Order=0)]
        public DetiInteract.Guide.DSDWS.getAulasRequestBody Body;
        
        public getAulasRequest() {
        }
        
        public getAulasRequest(DetiInteract.Guide.DSDWS.getAulasRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://dsd.av.it.pt/dsdws")]
    public partial class getAulasRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int IDDepartamento;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public int IDSemestre;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public int Rev;
        
        public getAulasRequestBody() {
        }
        
        public getAulasRequestBody(int IDDepartamento, int IDSemestre, int Rev) {
            this.IDDepartamento = IDDepartamento;
            this.IDSemestre = IDSemestre;
            this.Rev = Rev;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getAulasResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getAulasResponse", Namespace="http://dsd.av.it.pt/dsdws", Order=0)]
        public DetiInteract.Guide.DSDWS.getAulasResponseBody Body;
        
        public getAulasResponse() {
        }
        
        public getAulasResponse(DetiInteract.Guide.DSDWS.getAulasResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://dsd.av.it.pt/dsdws")]
    public partial class getAulasResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public DetiInteract.DSDBroker.DSDWS.Aula[] getAulasResult;
        
        public getAulasResponseBody() {
        }
        
        public getAulasResponseBody(DetiInteract.DSDBroker.DSDWS.Aula[] getAulasResult) {
            this.getAulasResult = getAulasResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getTurmasHoraRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getTurmasHora", Namespace="http://dsd.av.it.pt/dsdws", Order=0)]
        public DetiInteract.Guide.DSDWS.getTurmasHoraRequestBody Body;
        
        public getTurmasHoraRequest() {
        }
        
        public getTurmasHoraRequest(DetiInteract.Guide.DSDWS.getTurmasHoraRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://dsd.av.it.pt/dsdws")]
    public partial class getTurmasHoraRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int IDDepartamento;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public int IDSemestre;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public int Rev;
        
        public getTurmasHoraRequestBody() {
        }
        
        public getTurmasHoraRequestBody(int IDDepartamento, int IDSemestre, int Rev) {
            this.IDDepartamento = IDDepartamento;
            this.IDSemestre = IDSemestre;
            this.Rev = Rev;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getTurmasHoraResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getTurmasHoraResponse", Namespace="http://dsd.av.it.pt/dsdws", Order=0)]
        public DetiInteract.Guide.DSDWS.getTurmasHoraResponseBody Body;
        
        public getTurmasHoraResponse() {
        }
        
        public getTurmasHoraResponse(DetiInteract.Guide.DSDWS.getTurmasHoraResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://dsd.av.it.pt/dsdws")]
    public partial class getTurmasHoraResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public DetiInteract.DSDBroker.DSDWS.TurmaHora[] getTurmasHoraResult;
        
        public getTurmasHoraResponseBody() {
        }
        
        public getTurmasHoraResponseBody(DetiInteract.DSDBroker.DSDWS.TurmaHora[] getTurmasHoraResult) {
            this.getTurmasHoraResult = getTurmasHoraResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getWishListRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getWishList", Namespace="http://dsd.av.it.pt/dsdws", Order=0)]
        public DetiInteract.Guide.DSDWS.getWishListRequestBody Body;
        
        public getWishListRequest() {
        }
        
        public getWishListRequest(DetiInteract.Guide.DSDWS.getWishListRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://dsd.av.it.pt/dsdws")]
    public partial class getWishListRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int IDDepartamento;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public int IDSemestre;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public int Rev;
        
        public getWishListRequestBody() {
        }
        
        public getWishListRequestBody(int IDDepartamento, int IDSemestre, int Rev) {
            this.IDDepartamento = IDDepartamento;
            this.IDSemestre = IDSemestre;
            this.Rev = Rev;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getWishListResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getWishListResponse", Namespace="http://dsd.av.it.pt/dsdws", Order=0)]
        public DetiInteract.Guide.DSDWS.getWishListResponseBody Body;
        
        public getWishListResponse() {
        }
        
        public getWishListResponse(DetiInteract.Guide.DSDWS.getWishListResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://dsd.av.it.pt/dsdws")]
    public partial class getWishListResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public DetiInteract.DSDBroker.DSDWS.WishList[] getWishListResult;
        
        public getWishListResponseBody() {
        }
        
        public getWishListResponseBody(DetiInteract.DSDBroker.DSDWS.WishList[] getWishListResult) {
            this.getWishListResult = getWishListResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WSSoapChannel : DetiInteract.Guide.DSDWS.WSSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WSSoapClient : System.ServiceModel.ClientBase<DetiInteract.Guide.DSDWS.WSSoap>, DetiInteract.Guide.DSDWS.WSSoap {
        
        public WSSoapClient() {
        }
        
        public WSSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WSSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WSSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WSSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        DetiInteract.Guide.DSDWS.getSemestresResponse DetiInteract.Guide.DSDWS.WSSoap.getSemestres(DetiInteract.Guide.DSDWS.getSemestresRequest request) {
            return base.Channel.getSemestres(request);
        }
        
        public DetiInteract.DSDBroker.DSDWS.Semestre[] getSemestres(int Rev) {
            DetiInteract.Guide.DSDWS.getSemestresRequest inValue = new DetiInteract.Guide.DSDWS.getSemestresRequest();
            inValue.Body = new DetiInteract.Guide.DSDWS.getSemestresRequestBody();
            inValue.Body.Rev = Rev;
            DetiInteract.Guide.DSDWS.getSemestresResponse retVal = ((DetiInteract.Guide.DSDWS.WSSoap)(this)).getSemestres(inValue);
            return retVal.Body.getSemestresResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        DetiInteract.Guide.DSDWS.getTiposSalaResponse DetiInteract.Guide.DSDWS.WSSoap.getTiposSala(DetiInteract.Guide.DSDWS.getTiposSalaRequest request) {
            return base.Channel.getTiposSala(request);
        }
        
        public DetiInteract.DSDBroker.DSDWS.TipoSala[] getTiposSala(int Rev) {
            DetiInteract.Guide.DSDWS.getTiposSalaRequest inValue = new DetiInteract.Guide.DSDWS.getTiposSalaRequest();
            inValue.Body = new DetiInteract.Guide.DSDWS.getTiposSalaRequestBody();
            inValue.Body.Rev = Rev;
            DetiInteract.Guide.DSDWS.getTiposSalaResponse retVal = ((DetiInteract.Guide.DSDWS.WSSoap)(this)).getTiposSala(inValue);
            return retVal.Body.getTiposSalaResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        DetiInteract.Guide.DSDWS.getSalasResponse DetiInteract.Guide.DSDWS.WSSoap.getSalas(DetiInteract.Guide.DSDWS.getSalasRequest request) {
            return base.Channel.getSalas(request);
        }
        
        public DetiInteract.DSDBroker.DSDWS.Sala[] getSalas(int IDDepartamento, int Rev) {
            DetiInteract.Guide.DSDWS.getSalasRequest inValue = new DetiInteract.Guide.DSDWS.getSalasRequest();
            inValue.Body = new DetiInteract.Guide.DSDWS.getSalasRequestBody();
            inValue.Body.IDDepartamento = IDDepartamento;
            inValue.Body.Rev = Rev;
            DetiInteract.Guide.DSDWS.getSalasResponse retVal = ((DetiInteract.Guide.DSDWS.WSSoap)(this)).getSalas(inValue);
            return retVal.Body.getSalasResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        DetiInteract.Guide.DSDWS.getCursosResponse DetiInteract.Guide.DSDWS.WSSoap.getCursos(DetiInteract.Guide.DSDWS.getCursosRequest request) {
            return base.Channel.getCursos(request);
        }
        
        public DetiInteract.DSDBroker.DSDWS.Curso[] getCursos(int IDDepartamento, int Rev) {
            DetiInteract.Guide.DSDWS.getCursosRequest inValue = new DetiInteract.Guide.DSDWS.getCursosRequest();
            inValue.Body = new DetiInteract.Guide.DSDWS.getCursosRequestBody();
            inValue.Body.IDDepartamento = IDDepartamento;
            inValue.Body.Rev = Rev;
            DetiInteract.Guide.DSDWS.getCursosResponse retVal = ((DetiInteract.Guide.DSDWS.WSSoap)(this)).getCursos(inValue);
            return retVal.Body.getCursosResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        DetiInteract.Guide.DSDWS.getDepartamentosResponse DetiInteract.Guide.DSDWS.WSSoap.getDepartamentos(DetiInteract.Guide.DSDWS.getDepartamentosRequest request) {
            return base.Channel.getDepartamentos(request);
        }
        
        public DetiInteract.DSDBroker.DSDWS.Departamento[] getDepartamentos(int Rev) {
            DetiInteract.Guide.DSDWS.getDepartamentosRequest inValue = new DetiInteract.Guide.DSDWS.getDepartamentosRequest();
            inValue.Body = new DetiInteract.Guide.DSDWS.getDepartamentosRequestBody();
            inValue.Body.Rev = Rev;
            DetiInteract.Guide.DSDWS.getDepartamentosResponse retVal = ((DetiInteract.Guide.DSDWS.WSSoap)(this)).getDepartamentos(inValue);
            return retVal.Body.getDepartamentosResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        DetiInteract.Guide.DSDWS.getAreasResponse DetiInteract.Guide.DSDWS.WSSoap.getAreas(DetiInteract.Guide.DSDWS.getAreasRequest request) {
            return base.Channel.getAreas(request);
        }
        
        public DetiInteract.DSDBroker.DSDWS.Area[] getAreas(int Rev) {
            DetiInteract.Guide.DSDWS.getAreasRequest inValue = new DetiInteract.Guide.DSDWS.getAreasRequest();
            inValue.Body = new DetiInteract.Guide.DSDWS.getAreasRequestBody();
            inValue.Body.Rev = Rev;
            DetiInteract.Guide.DSDWS.getAreasResponse retVal = ((DetiInteract.Guide.DSDWS.WSSoap)(this)).getAreas(inValue);
            return retVal.Body.getAreasResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        DetiInteract.Guide.DSDWS.getSubAreasResponse DetiInteract.Guide.DSDWS.WSSoap.getSubAreas(DetiInteract.Guide.DSDWS.getSubAreasRequest request) {
            return base.Channel.getSubAreas(request);
        }
        
        public DetiInteract.DSDBroker.DSDWS.SubArea[] getSubAreas(int Rev) {
            DetiInteract.Guide.DSDWS.getSubAreasRequest inValue = new DetiInteract.Guide.DSDWS.getSubAreasRequest();
            inValue.Body = new DetiInteract.Guide.DSDWS.getSubAreasRequestBody();
            inValue.Body.Rev = Rev;
            DetiInteract.Guide.DSDWS.getSubAreasResponse retVal = ((DetiInteract.Guide.DSDWS.WSSoap)(this)).getSubAreas(inValue);
            return retVal.Body.getSubAreasResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        DetiInteract.Guide.DSDWS.getDocentesResponse DetiInteract.Guide.DSDWS.WSSoap.getDocentes(DetiInteract.Guide.DSDWS.getDocentesRequest request) {
            return base.Channel.getDocentes(request);
        }
        
        public DetiInteract.DSDBroker.DSDWS.Docente[] getDocentes(int IDDepartamento, int Rev) {
            DetiInteract.Guide.DSDWS.getDocentesRequest inValue = new DetiInteract.Guide.DSDWS.getDocentesRequest();
            inValue.Body = new DetiInteract.Guide.DSDWS.getDocentesRequestBody();
            inValue.Body.IDDepartamento = IDDepartamento;
            inValue.Body.Rev = Rev;
            DetiInteract.Guide.DSDWS.getDocentesResponse retVal = ((DetiInteract.Guide.DSDWS.WSSoap)(this)).getDocentes(inValue);
            return retVal.Body.getDocentesResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        DetiInteract.Guide.DSDWS.getDocentesAnoResponse DetiInteract.Guide.DSDWS.WSSoap.getDocentesAno(DetiInteract.Guide.DSDWS.getDocentesAnoRequest request) {
            return base.Channel.getDocentesAno(request);
        }
        
        public DetiInteract.DSDBroker.DSDWS.DocenteAno[] getDocentesAno(int IDDepartamento, int IDSemestre, int Rev) {
            DetiInteract.Guide.DSDWS.getDocentesAnoRequest inValue = new DetiInteract.Guide.DSDWS.getDocentesAnoRequest();
            inValue.Body = new DetiInteract.Guide.DSDWS.getDocentesAnoRequestBody();
            inValue.Body.IDDepartamento = IDDepartamento;
            inValue.Body.IDSemestre = IDSemestre;
            inValue.Body.Rev = Rev;
            DetiInteract.Guide.DSDWS.getDocentesAnoResponse retVal = ((DetiInteract.Guide.DSDWS.WSSoap)(this)).getDocentesAno(inValue);
            return retVal.Body.getDocentesAnoResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        DetiInteract.Guide.DSDWS.getDisciplinasResponse DetiInteract.Guide.DSDWS.WSSoap.getDisciplinas(DetiInteract.Guide.DSDWS.getDisciplinasRequest request) {
            return base.Channel.getDisciplinas(request);
        }
        
        public DetiInteract.DSDBroker.DSDWS.Disciplina[] getDisciplinas(int IDDepartamento, int Rev) {
            DetiInteract.Guide.DSDWS.getDisciplinasRequest inValue = new DetiInteract.Guide.DSDWS.getDisciplinasRequest();
            inValue.Body = new DetiInteract.Guide.DSDWS.getDisciplinasRequestBody();
            inValue.Body.IDDepartamento = IDDepartamento;
            inValue.Body.Rev = Rev;
            DetiInteract.Guide.DSDWS.getDisciplinasResponse retVal = ((DetiInteract.Guide.DSDWS.WSSoap)(this)).getDisciplinas(inValue);
            return retVal.Body.getDisciplinasResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        DetiInteract.Guide.DSDWS.getDisciplinasAnoResponse DetiInteract.Guide.DSDWS.WSSoap.getDisciplinasAno(DetiInteract.Guide.DSDWS.getDisciplinasAnoRequest request) {
            return base.Channel.getDisciplinasAno(request);
        }
        
        public DetiInteract.DSDBroker.DSDWS.DisciplinaAno[] getDisciplinasAno(int IDDepartamento, int IDSemestre, int Rev) {
            DetiInteract.Guide.DSDWS.getDisciplinasAnoRequest inValue = new DetiInteract.Guide.DSDWS.getDisciplinasAnoRequest();
            inValue.Body = new DetiInteract.Guide.DSDWS.getDisciplinasAnoRequestBody();
            inValue.Body.IDDepartamento = IDDepartamento;
            inValue.Body.IDSemestre = IDSemestre;
            inValue.Body.Rev = Rev;
            DetiInteract.Guide.DSDWS.getDisciplinasAnoResponse retVal = ((DetiInteract.Guide.DSDWS.WSSoap)(this)).getDisciplinasAno(inValue);
            return retVal.Body.getDisciplinasAnoResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        DetiInteract.Guide.DSDWS.getTurmasResponse DetiInteract.Guide.DSDWS.WSSoap.getTurmas(DetiInteract.Guide.DSDWS.getTurmasRequest request) {
            return base.Channel.getTurmas(request);
        }
        
        public DetiInteract.DSDBroker.DSDWS.Turma[] getTurmas(int IDDepartamento, int IDSemestre, int Rev) {
            DetiInteract.Guide.DSDWS.getTurmasRequest inValue = new DetiInteract.Guide.DSDWS.getTurmasRequest();
            inValue.Body = new DetiInteract.Guide.DSDWS.getTurmasRequestBody();
            inValue.Body.IDDepartamento = IDDepartamento;
            inValue.Body.IDSemestre = IDSemestre;
            inValue.Body.Rev = Rev;
            DetiInteract.Guide.DSDWS.getTurmasResponse retVal = ((DetiInteract.Guide.DSDWS.WSSoap)(this)).getTurmas(inValue);
            return retVal.Body.getTurmasResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        DetiInteract.Guide.DSDWS.getAulasResponse DetiInteract.Guide.DSDWS.WSSoap.getAulas(DetiInteract.Guide.DSDWS.getAulasRequest request) {
            return base.Channel.getAulas(request);
        }
        
        public DetiInteract.DSDBroker.DSDWS.Aula[] getAulas(int IDDepartamento, int IDSemestre, int Rev) {
            DetiInteract.Guide.DSDWS.getAulasRequest inValue = new DetiInteract.Guide.DSDWS.getAulasRequest();
            inValue.Body = new DetiInteract.Guide.DSDWS.getAulasRequestBody();
            inValue.Body.IDDepartamento = IDDepartamento;
            inValue.Body.IDSemestre = IDSemestre;
            inValue.Body.Rev = Rev;
            DetiInteract.Guide.DSDWS.getAulasResponse retVal = ((DetiInteract.Guide.DSDWS.WSSoap)(this)).getAulas(inValue);
            return retVal.Body.getAulasResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        DetiInteract.Guide.DSDWS.getTurmasHoraResponse DetiInteract.Guide.DSDWS.WSSoap.getTurmasHora(DetiInteract.Guide.DSDWS.getTurmasHoraRequest request) {
            return base.Channel.getTurmasHora(request);
        }
        
        public DetiInteract.DSDBroker.DSDWS.TurmaHora[] getTurmasHora(int IDDepartamento, int IDSemestre, int Rev) {
            DetiInteract.Guide.DSDWS.getTurmasHoraRequest inValue = new DetiInteract.Guide.DSDWS.getTurmasHoraRequest();
            inValue.Body = new DetiInteract.Guide.DSDWS.getTurmasHoraRequestBody();
            inValue.Body.IDDepartamento = IDDepartamento;
            inValue.Body.IDSemestre = IDSemestre;
            inValue.Body.Rev = Rev;
            DetiInteract.Guide.DSDWS.getTurmasHoraResponse retVal = ((DetiInteract.Guide.DSDWS.WSSoap)(this)).getTurmasHora(inValue);
            return retVal.Body.getTurmasHoraResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        DetiInteract.Guide.DSDWS.getWishListResponse DetiInteract.Guide.DSDWS.WSSoap.getWishList(DetiInteract.Guide.DSDWS.getWishListRequest request) {
            return base.Channel.getWishList(request);
        }
        
        public DetiInteract.DSDBroker.DSDWS.WishList[] getWishList(int IDDepartamento, int IDSemestre, int Rev) {
            DetiInteract.Guide.DSDWS.getWishListRequest inValue = new DetiInteract.Guide.DSDWS.getWishListRequest();
            inValue.Body = new DetiInteract.Guide.DSDWS.getWishListRequestBody();
            inValue.Body.IDDepartamento = IDDepartamento;
            inValue.Body.IDSemestre = IDSemestre;
            inValue.Body.Rev = Rev;
            DetiInteract.Guide.DSDWS.getWishListResponse retVal = ((DetiInteract.Guide.DSDWS.WSSoap)(this)).getWishList(inValue);
            return retVal.Body.getWishListResult;
        }
    }
}
